### ISSUE TITLE
classic seo v2.2.0-alpha

### ISSUE THREAD

**Issue by Soenke2** [ClassicPress/classicpress-seo#158]
Hallo,

in the backend, the following deprecations are displayed after updating to php 8.1 using v2.2.0-alpa and v2-20230712:

-> post -> Screen Element ClassicSEO -> Tab general above Preview:

```
Deprecated: Calling static trait method Classic_SEO\Helpers\WordPress::get_post_type is deprecated, it should only be called on a class using the trait in /.../wp-content/plugins/classicpress-seo/includes/admin/class-serp-preview.php on line 101

Deprecated: Calling static trait method Classic_SEO\Helpers\WordPress::post_type_from_globals is deprecated, it should only be called on a class using the trait in /.../wp-content/plugins/classicpress-seo/includes/helpers/class-wordpress.php on line 57
```

**Comment by xxsimoxx** [comment]
@Soenke2 can you please check if the related PR fixes this?

**Comment by Soenke2** [comment]
everything works fine with php 8.1 - the messages have disappeared

**Comment by Soenke2** [comment]
everything works fine with php 8.1 - the messages have disappeared

 

Von: SIMONE FIORAVANTI ***@***.***> 
Gesendet: Donnerstag, 13. Juli 2023 15:02
An: ClassicPress/classicpress-seo ***@***.***>
Cc: Soenke2 ***@***.***>; Mention ***@***.***>
Betreff: Re: [ClassicPress/classicpress-seo] classic seo v2.2.0-alpha (Issue #158)

 

Please try the new alpha release <https://github.com/ClassicPress/classicpress-seo/releases/download/v2.2.0-alpha.1/classicpress-seo.zip> .
